# Generated by Django 4.0.2 on 2022-02-15 19:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Coin",
                "verbose_name_plural": "Coins",
            },
        ),
        migrations.CreateModel(
            name="CoinMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("operation_id", models.IntegerField()),
                ("date", models.DateTimeField(default=0)),
                (
                    "high",
                    models.DecimalField(decimal_places=20, default=0, max_digits=40),
                ),
                (
                    "low",
                    models.DecimalField(decimal_places=20, default=0, max_digits=40),
                ),
                (
                    "open",
                    models.DecimalField(decimal_places=20, default=0, max_digits=40),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=20, default=0, max_digits=40),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=20, default=0, max_digits=40),
                ),
                (
                    "marketcap",
                    models.DecimalField(decimal_places=20, default=0, max_digits=40),
                ),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data",
                        to="example.coin",
                    ),
                ),
            ],
            options={
                "verbose_name": "CoinMarketData",
                "verbose_name_plural": "CoinMarketData",
            },
        ),
    ]
